vich_uploader:
    db_driver: orm

    mappings:
        todolist_images:
            uri_prefix: /images/todolist
            upload_destination: '%kernel.project_dir%/public/images/todolist'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
